# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run apiScheduler

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "19 12 * * *"
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
      TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      TRELLO_BOARD: ${{ secrets.TRELLO_BOARD }}
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Download Tasklist from artifact repository
      uses: actions/download-artifact@v3
      with:
        name: Tasklist

    - name: Run apiScheduler.py
      run: |
        python Python/apiScheduler.py
    
    - name: Upload tasklist.yml artifact
      uses: actions/upload-artifact@v3
      with:
        name: Tasklist
        path: tasklist.yml