# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run apiScheduler

on:
  push:
    branches: 
    - main
  schedule:
  - cron: "19 12 * * *"
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      TRELLO_KEY: ${{ secrets.TRELLO_KEY }}
      TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      TRELLO_BOARD: ${{ secrets.TRELLO_BOARD }}
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        ref: actions/TasklistUpdates
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run apiScheduler.py
      run: |
        python apiScheduler.py

    - name: Update Tasklist in actions/TasklistUpdates
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "github-actions"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Update Tasklist Run Dates" -a
           git push
           echo "::set-output name=push::true"
        fi
      shell: bash